name: Test new Implementation
on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    name: Build and Test Front-End Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      # TODO: Coming soon